### ISSUE TITLE
Improve snapshot integration

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#2469]
```[tasklist]
### Tasks
- [ ] https://github.com/lensterxyz/lenster/issues/2470
- [ ] https://github.com/lensterxyz/lenster/issues/2471
- [ ] https://github.com/lensterxyz/lenster/issues/2472
- [ ] https://github.com/lensterxyz/lenster/issues/2481
- [x] Remove snapshot URL if the widget is rendered
- [x] Add loading states for voting
```
