### ISSUE TITLE
Lenster Spaces 🏘️

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#3038]
```[tasklist]
### Tasks
- [ ] https://github.com/lensterxyz/lenster/issues/3039
- [ ] https://github.com/lensterxyz/lenster/issues/3040
- [ ] https://github.com/lensterxyz/lenster/issues/3041
- [ ] https://github.com/lensterxyz/lenster/issues/3042
- [ ] https://github.com/lensterxyz/lenster/issues/3043
- [ ] https://github.com/lensterxyz/lenster/issues/3044
- [ ] https://github.com/lensterxyz/lenster/issues/3098
- [ ] Check possibilities of space recording
```
