### ISSUE TITLE
Add space player modal

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#3041]
```[tasklist]
### Tasks
- [ ] Add signing feature for authenticated huddle experience
- [ ] Add scrollable modal with virtual list of users
- [ ] Add fixed view in bottom to add all CTA like talk, mute and leave buttons
```
