### ISSUE TITLE
Space creation in composer

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#3044]
```[tasklist]
### Tasks
- [x] Wrap with feature flag
- [x] Add basic space creator
- [x] Integrate with API
- [ ] Add big font for placeholder and title
- [ ] Limit space title length
- [ ] Able to pin a post
```
