### ISSUE TITLE
community fe: create community page

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#3318]
```[tasklist]
### Tasks
- [x] Add name
- [ ] Add handle with prefix as current URL
- [x] Add description
- [ ] Add twitter handle
- [ ] Add website URL
- [ ] Add community avatar
- [ ] Add NSFW check
```
