### ISSUE TITLE
community: add leafwatch events

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#3334]
```[tasklist]
### Tasks
- [ ] Create community
- [ ] Join community
- [ ] Update community
- [ ] Delete community
- [ ] Add community rules
- [ ] Update community rules
- [ ] update: New publication (pass community id as props)
```
